CONFIG_ZMK_KEYBOARD_NAME="PNCATENO"

CONFIG_ZMK_SLEEP=y

#rgb
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

CONFIG_ZMK_STUDIO_LOCKING=n

